node {
    
        
    stage('checkout') {
        git branch: '${BRANCH}', url: 'https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen.git'
    }
    
        
    
    stage('Deploy') {
        echo 'Deploying....'
        
        dir('docker-base') {
	        withCredentials([ usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERUSER', passwordVariable: 'DOCKERPASS' )]) {
	        	sh """
	        	cp ../sormas-stats-shinyapp/sormas-stats-app/renv.lock .
	            sudo docker build --pull --no-cache -t sormas-stats-base:${BRANCH} .
	            sudo docker login -u '${DOCKERUSER}' -p '${DOCKERPASS}' docker.io
	            sudo docker tag sormas-stats-base:${BRANCH} docker.io/hzibraunschweig/sormas-stats-base:${TAG}
	            sudo docker push docker.io/hzibraunschweig/sormas-stats-base:${TAG}
	            sudo docker logout docker.io
	            """      
	        }
        }
    }
}
