node {
    
        
    stage('checkout') {
        git branch: 'feature_SORGEN-89', url: 'https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen.git'
    }
    
        
    
    stage('Deploy') {
        echo 'Deploying....'
        
        dir('docker-base') {
	        withCredentials([ usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERUSER', passwordVariable: 'DOCKERPASS' )]) {
	        	sh """
	        	cp ../sormas-stats-shinyapp/sormas-stats-app/renv.lock .
	            sudo buildah bud --pull-always --no-cache -t sormas-stats-base .
	            sudo buildah login -u '${DOCKERUSER}' -p '${DOCKERPASS}' docker.io
	            sudo buildah push -f v2s2 sormas-stats-base hzibraunschweig/sormas-stats-base:latest
	            """                                                                                                                 
	        }
        }
    }
}
