# 
### loading packages ############
# if(!require(shiny)) install.packages("shiny", repos = "http://cran.us.r-project.org")
# if(!require(shinyWidgets)) install.packages("shinyWidgets", repos = "http://cran.us.r-project.org")
# if(!require(shinydashboard)) install.packages("shinydashboard", repos = "http://cran.us.r-project.org")
# if(!require(shinythemes)) install.packages("shinythemes", repos = "http://cran.us.r-project.org")
# 
# 
# if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
# if(!require(ggplot2)) install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# if(!require(RColorBrewer)) install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
# if(!require(plotly)) install.packages("plotly", repos = "http://cran.us.r-project.org")
# if(!require(visNetwork)) install.packages("visNetwork", repos = "http://cran.us.r-project.org")
# if(!require(extrafont)) install.packages("extrafont", repos = "http://cran.us.r-project.org")
# if(!require(rpart)) install.packages("rpart", repos = "http://cran.us.r-project.org")
# if(!require(ggthemes)) install.packages("ggthemes", repos = "http://cran.us.r-project.org")
# if(!require(lubridate)) install.packages("lubridate", repos = "http://cran.us.r-project.org")
# if(!require(Hmisc)) install.packages("Hmisc", repos = "http://cran.us.r-project.org")
# if(!require(gdata)) install.packages("gdata", repos = "http://cran.us.r-project.org")
# if(!require(scales)) install.packages("scales", repos = "http://cran.us.r-project.org")
# if(!require(EpiEstim)) install_github("annecori/EpiEstim", force = TRUE)
# if(!require(incidence))  install.packages("incidence",  repos = "http://cran.us.r-project.org")
# if(!require(tidyr))  install.packages("tidyr",  repos = "http://cran.us.r-project.org")
# if (!require("DT")) install.packages('DT')



#if(!require(XML2)) install.packages("XML2", repos = "http://cran.us.r-project.org")
#if(!require(reshape2)) install.packages("reshape2", repos = "http://cran.us.r-project.org")

library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(shinycssloaders)


library(visNetwork)
library(ggplot2)
library(dplyr)
library(plotly)
library(extrafont)
library(rpart)
library(RColorBrewer)
library(webshot) # for plot export
library(ggthemes)
library(lubridate)
library(Hmisc)
library(gdata)
library(scales)
library(EpiEstim)
library(incidence)
library(tidyr)
library(DT)  

library(rgdal)
library(maps)
library(maptools)
library(mapdata)
library(ggplot2)
library(foreign)    
library(sp)
library(broom)
library(stringi)

library(ggmap)
library(rgeos)
library(tmap)
#library(sf)
library(lattice)
library(RPostgreSQL)
library(igraph)
library(leaflet)
library(fitdistrplus) 
library(tidyverse)
