library(renv)
library(shiny)
library(shinydashboard)
library(glue)
library(shinythemes)
library(shinyWidgets)
library(shinyjs)
library(shinycssloaders)
library(shiny.i18n) # for translation

library(visNetwork)
library(ggplot2)
library(dplyr)
library(plotly)
library(extrafont)
library(fontawesome)
library(rpart)
library(RColorBrewer)
library(webshot) # for plot export
library(ggthemes)
library(lubridate)
library(Hmisc)
library(gdata)
library(scales)
library(EpiEstim)
library(incidence)
library(tidyr)
library(DT)
library(rgdal)
library(stringi)
library(RPostgreSQL)
library(igraph)
library(fitdistrplus)
library(tidyverse)

# map packages
# library(maps)
# library(maptools)
# library(mapdata)
# library(foreign)
# library(sp)
# library(broom)
# library(ggmap)
# library(rgeos)
#library(tmap)
#library(sf)
#library(lattice)
#library(leaflet)

# Authentication packaged
#library(sodium)
#library(shinyauthr)
#library(attempt)
#library(config) 